/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainPage.java
 *
 * Created on Mar 12, 2011, 8:11:21 PM
 */

package GUI;

import AdtFrm.MainFrm;
import AppointmentGUI.ApptCalender;
import DBConnection.DBConnection;
import Helper.Session;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication1.Consultation;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
/**
 *
 * @author phoebe
 */

public class MainPage extends javax.swing.JFrame {
    private String id;
    private String staffName;
    
    public void setDesign() {
//        ImageIcon background = new ImageIcon("utem2.png");
//        JLabel label = new JLabel();
//        label.setBounds(0, 0, 600, 452);
//        label.setIcon(background);
//
//        back1.setLayout(null);
//        back1.add(label);
//        back1.remove(0);
    }

    /** Creates new form MainPage */
    public MainPage() {
        initComponents();
        setRole();
        //setButtons();
        setDesign();
    }
    
    private void hideAllBtn() {
        btnPAS.setEnabled(false);
        btnPatientAppointment.setEnabled(false);
        btn_pms.setEnabled(false);
        btn_consultation.setEnabled(false);
        btn_pharmacy.setEnabled(false);
        btn_adt.setEnabled(false);
        btn_CodeMaintenance.setEnabled(false);
        btn_snomed.setEnabled(false);
        btn_report.setEnabled(false);
        btn_med_chkup.setEnabled(false);
        btn_datamanagement.setEnabled(false);
    }
    
    private void showAllBtn() {
        btnPAS.setEnabled(true);
        btnPatientAppointment.setEnabled(true);
        btn_pms.setEnabled(true);
        btn_consultation.setEnabled(true);
        btn_pharmacy.setEnabled(true);
        btn_adt.setEnabled(true);
        btn_CodeMaintenance.setEnabled(true);
        btn_snomed.setEnabled(true);
        btn_report.setEnabled(true);
        btn_med_chkup.setEnabled(true);
        btn_datamanagement.setEnabled(true);
    }

    private void setRole() {
        hideAllBtn();
        try {
            String role = Session.getData_user().get(20); // role code
            System.out.println("role:|"+role+"|");
            if (role.equals("SYSTEM ADMINISTRATOR")) {
//                btnPAS.setEnabled(true);
//                btn_CodeMaintenance.setEnabled(true);
//                btn_snomed.setEnabled(true);
//                btn_datamanagement.setEnabled(true);
//                btn_report.setEnabled(true);
//                btn_med_chkup.setEnabled(true);
//                btn_datamanagement.setEnabled(true);
                showAllBtn();
            } else if (role.equals("DOCTOR")) {
                btnPatientAppointment.setEnabled(true);
                btn_pms.setEnabled(true);
                btn_consultation.setEnabled(true);
                btn_adt.setEnabled(true);
                btn_report.setEnabled(true);
                btn_med_chkup.setEnabled(true);
                btn_datamanagement.setEnabled(true);
            } else if (role.equals("NURSE")) {
                btnPatientAppointment.setEnabled(true);
                btn_pms.setEnabled(true);
                btn_pharmacy.setEnabled(true);
                btn_datamanagement.setEnabled(true);
                btn_report.setEnabled(true);
            } else if (role.equals("NORMAL USER")) {
            } else if (role.equals("MANAGER")) {
            } else if (role.equals("SUPERVISOR")) {
            } else {
                showAllBtn();
            }
        } catch (Exception ex) {
            showAllBtn();
        }
    }
    
    public MainPage(String id) {
        initComponents();
        
        //get id value from main page
        this.id = id;
        
        setRole();
        //setButtons();
        setDesign();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        back1 = new javax.swing.JPanel();
        btn_med_chkup = new javax.swing.JButton();
        btnPAS = new javax.swing.JButton();
        btn_pharmacy = new javax.swing.JButton();
        btn_consultation = new javax.swing.JButton();
        btn_snomed = new javax.swing.JButton();
        btn_datamanagement = new javax.swing.JButton();
        btn_adt = new javax.swing.JButton();
        btnPatientAppointment = new javax.swing.JButton();
        btn_pms = new javax.swing.JButton();
        btn_CodeMaintenance = new javax.swing.JButton();
        btn_logOut = new javax.swing.JButton();
        btn_report = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_CodeMaintenance1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Clinical Support System");
        setResizable(false);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(51, 51, 255));
        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Clinical Support System");

        back1.setPreferredSize(new java.awt.Dimension(600, 600));

        btn_med_chkup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/medicalchkup.png"))); // NOI18N
        btn_med_chkup.setToolTipText("Medical Checkup Entry");
        btn_med_chkup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_med_chkupActionPerformed(evt);
            }
        });

        btnPAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/humanresource.png"))); // NOI18N
        btnPAS.setToolTipText("Human Rescources");
        btnPAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPASActionPerformed(evt);
            }
        });

        btn_pharmacy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pharmacy.png"))); // NOI18N
        btn_pharmacy.setToolTipText("Pharmacy Information System");
        btn_pharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pharmacyActionPerformed(evt);
            }
        });

        btn_consultation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/consultation.png"))); // NOI18N
        btn_consultation.setToolTipText("Patient Consultation");
        btn_consultation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultationActionPerformed(evt);
            }
        });

        btn_snomed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/snomed.png"))); // NOI18N
        btn_snomed.setToolTipText("Snomed Maintenance");
        btn_snomed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_snomedActionPerformed(evt);
            }
        });

        btn_datamanagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/datamanagement.png"))); // NOI18N
        btn_datamanagement.setToolTipText("Data Management");
        btn_datamanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datamanagementActionPerformed(evt);
            }
        });

        btn_adt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/admitdischarge.png"))); // NOI18N
        btn_adt.setToolTipText("Admit, Discharge and Transfer System");
        btn_adt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adtActionPerformed(evt);
            }
        });

        btnPatientAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/appointment2.png"))); // NOI18N
        btnPatientAppointment.setToolTipText("Patient Appointment");
        btnPatientAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientAppointmentActionPerformed(evt);
            }
        });

        btn_pms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pms2.png"))); // NOI18N
        btn_pms.setToolTipText("Patient Management System");
        btn_pms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pmsActionPerformed(evt);
            }
        });

        btn_CodeMaintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/systemadmin.png"))); // NOI18N
        btn_CodeMaintenance.setToolTipText("System Administration");
        btn_CodeMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CodeMaintenanceActionPerformed(evt);
            }
        });

        btn_logOut.setText("Log Out");
        btn_logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logOutActionPerformed(evt);
            }
        });

        btn_report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/reports.png"))); // NOI18N
        btn_report.setToolTipText("Report");
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_CodeMaintenance1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/12.png"))); // NOI18N
        btn_CodeMaintenance1.setToolTipText("Procedure Order System");
        btn_CodeMaintenance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CodeMaintenance1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout back1Layout = new javax.swing.GroupLayout(back1);
        back1.setLayout(back1Layout);
        back1Layout.setHorizontalGroup(
            back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(back1Layout.createSequentialGroup()
                        .addComponent(btn_logOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(back1Layout.createSequentialGroup()
                        .addComponent(btnPAS, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPatientAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_med_chkup, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_snomed, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(back1Layout.createSequentialGroup()
                        .addComponent(btn_pms, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_consultation, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_pharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_report, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(back1Layout.createSequentialGroup()
                        .addComponent(btn_datamanagement, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_adt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_CodeMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_CodeMaintenance1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        back1Layout.setVerticalGroup(
            back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPAS, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPatientAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_med_chkup, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_snomed, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_pms, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_consultation, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_pharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_report, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(back1Layout.createSequentialGroup()
                        .addGroup(back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_datamanagement, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_adt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_CodeMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_logOut)
                            .addComponent(jButton1)))
                    .addComponent(btn_CodeMaintenance1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(566, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pharmacyActionPerformed
        // TODO add your handling code here:
        //Connection conn = DBConnection.getConnInstance(); //get connection

        staffName = DBConnection.getStaffNameAndID(id); //get staffName

        Pharmacy pharmacy = new Pharmacy(id, staffName); //pass id and staffName to pharmacy
        pharmacy.setVisible(true);
        this.dispose(); //close this form
    }//GEN-LAST:event_btn_pharmacyActionPerformed

    private void btn_logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logOutActionPerformed
        // TODO add your handling code here:
        //back to login page and close this form
        Session.logout();
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logOutActionPerformed

    private void btn_pmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pmsActionPerformed
        // TODO add your handling code here:
        Registration page = new Registration();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_pmsActionPerformed

    private void btn_adtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adtActionPerformed
        // TODO add your handling code here:
        MainFrm mainFrm = new MainFrm();
        mainFrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_adtActionPerformed

    private void btn_consultationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultationActionPerformed
        // TODO add your handling code here:
        Consultation consultation = new Consultation();
        consultation.setVisible(true);
        //Lifetime_Health_Summary lhs = new Lifetime_Health_Summary();
        //lhs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_consultationActionPerformed

    private void btnPASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPASActionPerformed
        // TODO add your handling code here:
        DialogStaffPage page;

        try {
            page = new DialogStaffPage();
            page.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
         

        this.dispose();
    }//GEN-LAST:event_btnPASActionPerformed

    private void btn_CodeMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CodeMaintenanceActionPerformed
        // TODO add your handling code here:
        CodeMaintainance cm = new CodeMaintainance();
        cm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CodeMaintenanceActionPerformed

    private void btnPatientAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientAppointmentActionPerformed
        // TODO add your handling code here:
       ApptCalender AppointmentCalender = new ApptCalender();
       AppointmentCalender.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnPatientAppointmentActionPerformed

    private void btn_snomedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_snomedActionPerformed
        // TODO add your handling code here:
        
        snomedUpdate snmd = new snomedUpdate();
        snmd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_snomedActionPerformed

    private void btn_datamanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datamanagementActionPerformed
        DataManagement dm = new DataManagement();
        dm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_datamanagementActionPerformed

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed
        ReportMenu reportMenu = new ReportMenu();
        reportMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_reportActionPerformed

    private void btn_med_chkupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_med_chkupActionPerformed
        // TODO add your handling code here:
        MedicalCheckup mc = new MedicalCheckup();
        mc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_med_chkupActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FacilityPage facipage = new FacilityPage(id);
        facipage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_CodeMaintenance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CodeMaintenance1ActionPerformed
        // TODO add your handling code here:
        new ProcedurePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_CodeMaintenance1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back1;
    private javax.swing.JButton btnPAS;
    private javax.swing.JButton btnPatientAppointment;
    private javax.swing.JButton btn_CodeMaintenance;
    private javax.swing.JButton btn_CodeMaintenance1;
    private javax.swing.JButton btn_adt;
    private javax.swing.JButton btn_consultation;
    private javax.swing.JButton btn_datamanagement;
    private javax.swing.JButton btn_logOut;
    private javax.swing.JButton btn_med_chkup;
    private javax.swing.JButton btn_pharmacy;
    private javax.swing.JButton btn_pms;
    private javax.swing.JButton btn_report;
    private javax.swing.JButton btn_snomed;
    private javax.swing.JButton jButton1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables

}
