/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ApptCalender.java
 *
 * Created on May 12, 2012, 5:03:54 PM
 */

package AppointmentGUI;

import java.awt.BorderLayout;
import java.awt.Container;
import javax.swing.JPanel;

/**
 *
 * @author WC
 */
public class ApptCalender extends javax.swing.JFrame {


    /** Creates new form ApptCalender */
    public ApptCalender() {
       
        initComponents();
        apptCAL abc = new apptCAL(this);
        this.setLayout(new BorderLayout());
        this.add(abc,BorderLayout.CENTER);
        abc.setVisible(true);
        this.setPreferredSize(abc.preferredSize());
        this.validate();
        this.repaint();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1176, 649));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
//           apptCAL calPanel= new apptCAL();
//
//
//            panel1.add(calPanel);
//        panel1.setLayout(new BorderLayout());
//        panel1.add(calPanel, BorderLayout.CENTER);
//       calPanel.setVisible(true);
//        panel1.validate();
//         panel1.repaint();


    


    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApptCalender().setVisible(true);


            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
