/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication1;

import DBConnection.DBConnection;
import api.LookupController;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import library.Func;

/**
 *
 * @author End User
 */
public class Laboratory_Request extends javax.swing.JFrame {
    
    private static Consultation cons;

    /**
     * Creates new form Laboratory_Request
     */
    public Laboratory_Request(Consultation cons) {
        initComponents();
        
        this.cons = cons;
        
        setLabRequest();
    }
    
    public void accept_button_lio() {
        String lio[] = new String[3];
        for (int i = 0; i < 3; i++) {
            lio[i] = "";
        }
        
        for (int i = 0; i < cons.sizeLRPK; i++) {
            if (cons.cbxPK[i].isSelected()) {
                lio[0] += cons.cbxPK[i].getText() + ", ";
                set_accept_button_lio("Chemist Patology", cons.cbxPK[i].getText());
            }
        }
        for (int i = 0; i < cons.sizeLRKL; i++) {
            if (cons.cbxKL[i].isSelected()) {
                lio[1] += cons.cbxKL[i].getText() + ", ";
                set_accept_button_lio("Clinical", cons.cbxKL[i].getText());
            }
        }
        for (int i = 0; i < cons.sizeLRHM; i++) {
            if (cons.cbxHM[i].isSelected()) {
                lio[2] += cons.cbxHM[i].getText() + ", ";
                set_accept_button_lio("Hematology", cons.cbxHM[i].getText());
            }
        }
    }
    
    private DefaultComboBoxModel UniCBmodel;
    
    public void getLookupTable() {
        try {
            LookupController CBoxloader = new LookupController();
            
            UniCBmodel = new DefaultComboBoxModel();
            UniCBmodel = CBoxloader.getLookupReferences("0081", "Health Facility", true);
            cbx_health_facility1.setModel(UniCBmodel);
            
            UniCBmodel = new DefaultComboBoxModel();
            UniCBmodel = CBoxloader.getLookupReferences("0072", "Discipline", true);
            cbx_discipline1.setModel(UniCBmodel);
            
            UniCBmodel = new DefaultComboBoxModel();
            UniCBmodel = CBoxloader.getLookupReferences("0071", "Sub Discipline", true);
            cbx_sub_discipline1.setModel(UniCBmodel);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Consultation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Consultation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_lab_req_1 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        pnl_patologi_kimia2 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        pnl_klinikal1 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        pnl_hematologi1 = new javax.swing.JPanel();
        jPanel71 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        cbx_priority = new javax.swing.JComboBox();
        txt_patient_condition1 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        cbx_health_facility1 = new javax.swing.JComboBox();
        jLabel69 = new javax.swing.JLabel();
        cbx_discipline1 = new javax.swing.JComboBox();
        jLabel70 = new javax.swing.JLabel();
        cbx_sub_discipline1 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel71 = new javax.swing.JLabel();
        jScrollPane83 = new javax.swing.JScrollPane();
        txt_notes1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_lab_req_1.setBackground(new java.awt.Color(173, 182, 200));

        jLabel82.setText("Chemist Patology");

        pnl_patologi_kimia2.setBackground(new java.awt.Color(173, 182, 200));
        pnl_patologi_kimia2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_patologi_kimia2.setPreferredSize(new java.awt.Dimension(150, 200));

        javax.swing.GroupLayout pnl_patologi_kimia2Layout = new javax.swing.GroupLayout(pnl_patologi_kimia2);
        pnl_patologi_kimia2.setLayout(pnl_patologi_kimia2Layout);
        pnl_patologi_kimia2Layout.setHorizontalGroup(
            pnl_patologi_kimia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        pnl_patologi_kimia2Layout.setVerticalGroup(
            pnl_patologi_kimia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );

        jLabel61.setText("Clinical");

        pnl_klinikal1.setBackground(new java.awt.Color(173, 182, 200));
        pnl_klinikal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_klinikal1.setPreferredSize(new java.awt.Dimension(150, 200));

        javax.swing.GroupLayout pnl_klinikal1Layout = new javax.swing.GroupLayout(pnl_klinikal1);
        pnl_klinikal1.setLayout(pnl_klinikal1Layout);
        pnl_klinikal1Layout.setHorizontalGroup(
            pnl_klinikal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        pnl_klinikal1Layout.setVerticalGroup(
            pnl_klinikal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );

        jLabel63.setText("Hematology");

        pnl_hematologi1.setBackground(new java.awt.Color(173, 182, 200));
        pnl_hematologi1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_hematologi1.setPreferredSize(new java.awt.Dimension(150, 200));

        javax.swing.GroupLayout pnl_hematologi1Layout = new javax.swing.GroupLayout(pnl_hematologi1);
        pnl_hematologi1.setLayout(pnl_hematologi1Layout);
        pnl_hematologi1Layout.setHorizontalGroup(
            pnl_hematologi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        pnl_hematologi1Layout.setVerticalGroup(
            pnl_hematologi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );

        jPanel71.setBackground(new java.awt.Color(173, 182, 200));

        jLabel64.setText("Priority : ");

        jLabel65.setText("Patient Condition : ");

        cbx_priority.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Urgent", "I.C.U." }));

        jLabel68.setText("Health Facility : ");

        cbx_health_facility1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel69.setText("Discipline : ");

        cbx_discipline1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel70.setText("Sub-Discipline : ");

        cbx_sub_discipline1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton5.setText("Accept");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel71.setText("Comments : ");

        txt_notes1.setColumns(20);
        txt_notes1.setRows(5);
        jScrollPane83.setViewportView(txt_notes1);

        javax.swing.GroupLayout jPanel71Layout = new javax.swing.GroupLayout(jPanel71);
        jPanel71.setLayout(jPanel71Layout);
        jPanel71Layout.setHorizontalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel71Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel71Layout.createSequentialGroup()
                        .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel65)
                            .addComponent(jLabel64))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_patient_condition1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_priority, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel71Layout.createSequentialGroup()
                        .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel71Layout.createSequentialGroup()
                                .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel68)
                                    .addComponent(jLabel69)
                                    .addComponent(jLabel70))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbx_health_facility1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbx_discipline1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel71Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane83, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                            .addComponent(cbx_sub_discipline1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(jLabel71))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel71Layout.setVerticalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel71Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel71Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(jPanel71Layout.createSequentialGroup()
                        .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel64)
                            .addComponent(cbx_priority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel65)
                            .addComponent(txt_patient_condition1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel68)
                            .addComponent(cbx_health_facility1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbx_discipline1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel69))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbx_sub_discipline1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel70))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel71)
                    .addComponent(jScrollPane83, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_lab_req_1Layout = new javax.swing.GroupLayout(pnl_lab_req_1);
        pnl_lab_req_1.setLayout(pnl_lab_req_1Layout);
        pnl_lab_req_1Layout.setHorizontalGroup(
            pnl_lab_req_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_lab_req_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_lab_req_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_lab_req_1Layout.createSequentialGroup()
                        .addGroup(pnl_lab_req_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_patologi_kimia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel82))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_lab_req_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_klinikal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel61))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_lab_req_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel63)
                            .addComponent(pnl_hematologi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        pnl_lab_req_1Layout.setVerticalGroup(
            pnl_lab_req_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_lab_req_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_lab_req_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82)
                    .addComponent(jLabel61)
                    .addComponent(jLabel63))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_lab_req_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_klinikal1, 197, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_patologi_kimia2, 197, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_hematologi1, 197, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_lab_req_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_lab_req_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if(cons.checkPatient()) return;
        if(cons.checkProblem().equals("|")) return;
        accept_button_lio();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void set_accept_button_lio(String parent, String test) {
        String data[] = {"Laboratory Investigation Order",
            "Type: " + Func.trim(parent),
            "Problem Code: " + Func.trim(cons.problemCode),
            "Problem: " + Func.trim(cons.problemDesc),
            "Lab Test: " + Func.trim(test),
            "Priority: " + Func.trim(cbx_priority.getSelectedItem().toString()),
            "Patient Condition: " + Func.trim(txt_patient_condition1.getText()),
            "Health Facility: " + Func.trim(cbx_health_facility1.getSelectedItem().toString()),
            "Discipline: " + Func.trim(cbx_discipline1.getSelectedItem().toString()),
            "Sub-Discipline: " + Func.trim(cbx_sub_discipline1.getSelectedItem().toString()),
            "Notes: " + Func.trim(txt_notes1.getText())
        };
        cons.setData(data, 15); //15 for Lab Investigation Order
    }
    
    public void setLabRequest() {
        ArrayList<String> lrPK = new ArrayList<String>();
        ArrayList<String> lrKL = new ArrayList<String>();
        ArrayList<String> lrHM = new ArrayList<String>();
        lrPK = DBConnection.getLabRequest("Patologi Kimia");
        lrKL = DBConnection.getLabRequest("Klinikal");
        lrHM = DBConnection.getLabRequest("Hematologi");
        pnl_patologi_kimia2.setLayout(new GridLayout(cons.sizeLR, 1));
        cons.sizeLRPK = lrPK.size();
        for (int i = 0; i < lrPK.size(); i++) {
            cons.cbxPK[i] = new JCheckBox();
            cons.cbxPK[i].setText(lrPK.get(i));
            pnl_patologi_kimia2.add(cons.cbxPK[i]);
        }
        pnl_klinikal1.setLayout(new GridLayout(cons.sizeLR, 1));
        cons.sizeLRKL = lrKL.size();
        for (int i = 0; i < lrKL.size(); i++) {
            cons.cbxKL[i] = new JCheckBox();
            cons.cbxKL[i].setText(lrKL.get(i));
            pnl_klinikal1.add(cons.cbxKL[i]);
        }
        pnl_hematologi1.setLayout(new GridLayout(cons.sizeLR, 1));
        cons.sizeLRHM = lrHM.size();
        for (int i = 0; i < lrHM.size(); i++) {
            cons.cbxHM[i] = new JCheckBox();
            cons.cbxHM[i].setText(lrPK.get(i));
            pnl_hematologi1.add(cons.cbxHM[i]);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laboratory_Request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laboratory_Request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laboratory_Request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laboratory_Request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laboratory_Request(cons).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox cbx_discipline1;
    public static javax.swing.JComboBox cbx_health_facility1;
    public static javax.swing.JComboBox cbx_priority;
    public static javax.swing.JComboBox cbx_sub_discipline1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JScrollPane jScrollPane83;
    public static javax.swing.JPanel pnl_hematologi1;
    public static javax.swing.JPanel pnl_klinikal1;
    public static javax.swing.JPanel pnl_lab_req_1;
    public static javax.swing.JPanel pnl_patologi_kimia2;
    public static javax.swing.JTextArea txt_notes1;
    public static javax.swing.JTextField txt_patient_condition1;
    // End of variables declaration//GEN-END:variables
}
